fixup! 5ccc55030d2d BACKPORT: pstore/ram: Introduce max_reason and convert dump_oops
../fs/pstore/ram.c:1023:15: error: no member named 'dump_oops' in 'struct ramoops_platform_data'
        ramoops_data.dump_oops = 1;
        ~~~~~~~~~~~~ ^
1 error generated.

../drivers/mtd/mtdoops.c:451:25: error: use of undeclared identifier 'KMSG_DUMP_POWEROFF'
        cxt->dump.max_reason = KMSG_DUMP_POWEROFF;
                               ^
1 error generated.

Ref: https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250/commit/044a90c924ddf1fec4d3c883bd45f2f1fae4a130

Change-Id: I1bcc86dd10285f6152d71f9441e892d06ac9e4ee