f2fs: Replace `f2fs_submit_bio()` with `__submit_bio()`
f2fs_submit_bio used to be a function that worked as a wrapper for
__submit_bio(). Since commit [1], f2fs_submit_bio has been removed
in favor of just using __submit_bio(). So, replace f2fs_submit_bio()
with __submit_bio().

This fixes the following compilation error when CONFIG_F2FS_FS_COMPRESSION=y:

ld.lld: error: undefined symbol: f2fs_submit_bio
>>> referenced by compress.c
>>>               f2fs/compress.o:(f2fs_prepare_compress_overwrite) in archive fs/built-in.a

[1]: 7fe5b4541fddc60d81c91273018d9432d77bc8c6 {"fs: {ext4, f2fs}: Remove CAF tracings"}

Change-Id: Ice3ec9a38ccf9c484d63c8e580abac124d42b11d
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
Signed-off-by: hridaya <hridaya@pixelos.net>